### ISSUE TITLE
Either website or the icons don't have the Konveyor color

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube#198]
@Akash-Nayak PTAL

**Comment by Akash-Nayak** [comment]
https://github.com/konveyor/konveyor.github.io/blob/8f3bc577b701c13667db325bea76bcf841865c4f/_sass/variables.scss#L7

https://github.com/konveyor/move2kube/blob/61a959a35c5646573f367506ddd9e80c3dfbab7b/_sass/color_schemes/konveyor.scss#L1

The primary header color used in the Konveyor website and the sidebar color in Move2Kube website is the same, but I think there is a gradient part in the Konveyor website because of the jekyll-cayman-theme and because of that the color changes from secondary color (left) to primary color (right).

<img width="1792" alt="Screenshot 2020-11-12 at 11 15 55 AM" src="https://user-images.githubusercontent.com/14867323/98900905-c0bbc880-24d8-11eb-8fad-c29ae5f4fe8d.png">


<img width="971" alt="Picture 1" src="https://user-images.githubusercontent.com/14867323/98901363-b0f0b400-24d9-11eb-8afd-36a06eaab5ef.png">

**Comment by Akash-Nayak** [comment]
The Move2Kube website will look somewhat like this if I apply the same gradient which is there in the Konveyor website.

<img width="1792" alt="Screenshot 2020-11-12 at 11 31 43 AM" src="https://user-images.githubusercontent.com/14867323/98901973-c61a1280-24da-11eb-9e9a-4c11bb8d96d9.png">

**Comment by Akash-Nayak** [comment]
PR https://github.com/konveyor/move2kube/pull/199 - Updated the logo and added gradient like Konveyor.
