### ISSUE TITLE
Get webpage to work fine in mobile browsers

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube#208]
**Is your feature request related to a problem? Please describe.**
Currently though the webpage works, some parts like Konveyor logo and others don't display right.

**Describe the solution you'd like**
Clean up and fix UI

**Describe alternatives you've considered**
The page is usage.

**Comment by Akash-Nayak** [comment]
I have updated the Konveyor logo. Looks like the issue is resolved now.
![mobile-screenshot2](https://user-images.githubusercontent.com/14867323/99114087-46915e00-2616-11eb-9cbb-402ef222cc6e.jpeg)

![mobile-screenshot1](https://user-images.githubusercontent.com/14867323/99114077-442f0400-2616-11eb-883c-1ba3746bc4d3.jpeg)

Can you please check it once @ashokponkumar?

**Comment by ashokponkumar** [comment]
Yes, I don't closed this issue after meeting your pr. Good work. Thanks

**Comment by Akash-Nayak** [comment]
Thank you. :-)
